export const QUESTION_TYPES = {
  FETCH_QUESTION_START: 'FETCH_QUESTION_START',
  FETCH_QUESTION_SUCCESS: 'FETCH_QUESTION_SUCCESS',
  FETCH_QUESTION_FAILED: 'FETCH_QUESTION_FAILED',
  CHANGE_PAGE_NUMBER: 'CHANGE_PAGE_NUMBER',
};
