export const QUESTION_TYPES = {
  FETCH_QUESTION_START: 'FETCH_QUESTION_START',
  FETCH_QUESTION_SUCCESS: 'FETCH_QUESTION_SUCCESS',
  FETCH_QUESTION_FAILED: 'FETCH_QUESTION_FAILED',
  NEXT_PAGE: 'NEXT_PAGE',
  BACK_TO_FIRST_PAGE: 'BACK_TO_FIRST_PAGE',
};
