export const TAG_TYPES = {
  FETCH_TAG_START: 'FETCH_TAG_START',
  FETCH_TAG_SUCCESS_WITH_DEFAULT_TAG: 'FETCH_TAG_SUCCESS_WITH_DEFAULT_TAG',
  FETCH_TAG_FAILED: 'FETCH_TAG_FAILED',
  SELECT_TAG: 'SELECT_TAG',
};
